In [1]:
import numpy as np

In [11]:
import numpy as np

class perceptron:
    def __init__(self, n_input, eta=0.2):
        self.w = np.zeros(n_input)
        self.b = 0
        self.eta = eta

    def activation(self, x):
        return np.where(x > 0, 1, 0)

    def predict(self, x):
        pred = np.dot(x, self.w) + self.b
        return self.activation(pred)

    def train(self, X, y, epochs=10):
        for epoch in range(epochs):
            for i in range(len(X)):
                pred = self.predict(X[i])
                error = y[i] - pred
                self.w += error * self.eta * X[i]
                self.b += error * self.eta

X = np.array([
    [0,0,0,0,0,0,0], # 0
    [0,0,0,0,0,0,1], # 1
    [0,0,0,0,0,1,0], # 2
    [0,0,0,0,0,1,1], # 3
    [0,0,0,0,1,0,0], # 4
    [0,0,0,0,1,0,1], # 5
    [0,0,0,0,1,1,0], # 6
    [0,0,0,0,1,1,1], # 7
    [0,0,0,1,0,0,0], # 8
    [0,0,0,1,0,0,1], # 9
])

Y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

p = perceptron(7, 0.2)
p.train(X, Y, 100)
print(p.predict(X))


[0 1 0 1 0 1 0 1 0 1]


In [3]:
np.array([[1,1,1,1],[1,1,1,1]]) @ np.array([2,2,2,2])

array([8, 8])

In [5]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])